#!/usr/bin/env python3
"""Generate ``real_data.py`` modules for the dpdk and net-drv fixtures.

Fetches two reference Bublik runs and, for every test, records the *exact*
per-iteration parameters and requirements so the synthetic fixtures can mirror
real runs. The output modules are consumed by ``fixtures.<suite>.fixture`` via
``core.synthetic_fixture.real_families``.

Usage::

    python tools/gen_real_data.py [--base https://ts-factory.io/bublik]

Re-run whenever the reference runs change. The emitted files are committed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterator
from urllib.parse import urlencode
from urllib.request import urlopen

DEFAULT_BASE = "https://ts-factory.io/bublik"

# Reference runs: (suite package dir, run id).
RUNS = (
    ("dpdk", 6022538),
    ("net_drv", 6581834),
)

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "src" / "fixtures"


def _get_json(url: str) -> Any:
    with urlopen(url, timeout=120) as response:  # noqa: S310 (trusted host)
        return json.load(response)


def _iter_tests(node: dict[str, Any]) -> Iterator[dict[str, Any]]:
    """Yield every ``type == "test"`` node in the stats tree, depth-first."""
    if node.get("type") == "test":
        yield node
    for child in node.get("children", ()):
        yield from _iter_tests(child)


def _selectors(tree_root: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """One representative ``{parent_id, exec_seqno}`` per test name."""
    selectors: dict[str, dict[str, Any]] = {}
    for test in _iter_tests(tree_root):
        name = test["test_name"]
        if name not in selectors:
            selectors[name] = {
                "parent_id": test["parent_id"],
                "exec_seqno": test["exec_seqno"],
            }
    return selectors


def _split_param(param: str) -> tuple[str, str]:
    """Split a ``"key=value"`` parameter on the first ``=`` (values may contain ``=``)."""
    key, _, value = param.partition("=")
    return key, value


def _fetch_iterations(base: str, name: str, selector: dict[str, Any]) -> list[dict[str, Any]]:
    query = urlencode(
        {
            "parent_id": selector["parent_id"],
            "test_name": name,
            "start_exec_seqno": selector["exec_seqno"],
        }
    )
    payload = _get_json(f"{base}/api/v2/results/?{query}")
    iterations: list[dict[str, Any]] = []
    for result in payload.get("results", ()):
        params = dict(_split_param(p) for p in result.get("parameters", ()))
        reqs = list(result.get("requirements", ()))
        iterations.append({"params": params, "reqs": reqs})
    return iterations


def _build(base: str, run_id: int) -> dict[str, list[dict[str, Any]]]:
    tree = _get_json(f"{base}/api/v2/runs/{run_id}/stats/?requirements=")
    root = tree["results"]
    selectors = _selectors(root)
    real: dict[str, list[dict[str, Any]]] = {}
    for name in sorted(selectors):
        real[name] = _fetch_iterations(base, name, selectors[name])
        print(f"  {name}: {len(real[name])} iterations")
    return real


def _emit(suite: str, run_id: int, real: dict[str, list[dict[str, Any]]]) -> Path:
    out = FIXTURES_DIR / suite / "real_data.py"
    header = (
        '"""Exact per-iteration parameters and requirements from a real run.\n\n'
        f"Generated by ``tools/gen_real_data.py`` from run {run_id}. Do not edit by\n"
        "hand; re-run the generator to refresh. Keyed by test name; each value is a\n"
        'list of iterations ``{"params": {...}, "reqs": [...]}``.\n"""\n\n'
        "from __future__ import annotations\n\n"
        "REAL: dict[str, list[dict]] = "
    )
    body = json.dumps(real, indent=4, ensure_ascii=False)
    out.write_text(header + body + "\n", encoding="utf-8")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default=DEFAULT_BASE, help="Bublik base URL")
    args = parser.parse_args()
    base = args.base.rstrip("/")

    for suite, run_id in RUNS:
        print(f"{suite}: fetching run {run_id} ...")
        real = _build(base, run_id)
        out = _emit(suite, run_id, real)
        total = sum(len(v) for v in real.values())
        print(f"{suite}: wrote {out} ({len(real)} tests, {total} iterations)\n")


if __name__ == "__main__":
    main()
